[package]
name = "immersion-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
firestore = "0.44.0"
poise = "0.6.1"
serde = "1.0.215"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
