name: Run Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

env: 
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TEST: Hello

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Make sure env vars are set up properly
        run: echo "VARS - $DISCORD_TOKEN - $DATABASE_URL - $TEST"

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Create .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run the app
        run: cargo run